version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gmaeon:latest
    container_name: gmaeon-container
    volumes:
      - .:/app
    ports:
      - "3333:3333"
